### PR TITLE
[#187355060] Admin Page for viewing users

### PR DESCRIPTION
**Pull request by shema-surge**
### 1: what does this PR do?

This PR creates an admin page for view users, updating roles and disabling users

### 2: Relevant Stories

#187355060

### Screenshots

20240724_11h36m41s_grim
20240724_11h36m52s_grim

### CODE REVIEW

**Review by lilika67 — APPROVED** [review]

**Comment by UmuhireJessie** [comment]
Can you add steps used to test your functionality? @shema-surge

**Review by Celestin4 — APPROVED** [review]

**Comment by UmuhireJessie** [comment]
Can you solve this @shema-surge 
Screenshot 2024-07-25 at 11 24 27

**Comment by shema-surge** [comment]
> Can you solve this @shema-surge Screenshot 2024-07-25 at 11 24 27

ok let me check it out

**Review by jniyonkuru — APPROVED** [review]

**Review by venuste-20002 — APPROVED** [review]

**Review by UmuhireJessie — CHANGES_REQUESTED** [review]
Can you remove one toast upon changing user role successfully
Screenshot 2024-07-25 at 20 38 21

**Review by UmuhireJessie — APPROVED** [review]

**Pull request merged**
